plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# SEO Stuff
author: Miranda
description: Messing around with Jekyll
lang: en
locale: en_GB
# url: "https://mscwilson.github.io/"
baseurl: ""

# build settings
permalink: blog/:year/:month/:day/:title/
sass:
  sass_dir: css
paginate: 3
paginate_path: "/blog/page:num"
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# RSS feed
feed:
  posts_limit: 20

# social icons
show_social_icons: true
github_username: mscwilson
twitter_username: someTwitterUser

include:
  - _pages

collections:
  - projects
