plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# SEO Stuff
title: Miranda Making Things
author: Miranda Wilson
description: >-
  I'm a cell biologist turned programmer. This site is my blog and portfolio: my coding journey and the things I've made.
lang: en
locale: en_GB
# url: "http://www.mirandawilson.tech"
email: miranda@mirandawilson.tech
github_username: mscwilson
baseurl: "/portfolio"

# build settings
permalink: blog/:year/:month/:day/:title/
sass:
  sass_dir: assets/css
  style: compressed
paginate: 10
paginate_path: "/blog/page:num"
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# RSS feed
feed:
  posts_limit: 20

# social icons
show_social_icons: true
github_username: mscwilson

include:
  - _pages

collections:
  - projects

tag_archive:
  type: liquid
  path: /blog/tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
