plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO Stuff
author: Miranda
description: Messing around with Jekyll
lang: en
locale: en_GB
# url: "https://mscwilson.github.io/portfolio"
baseurl: ""

# build settings
permalink: blog/:year/:month/:day/:title/
sass:
  sass_dir: css

# RSS feed
feed:
  posts_limit: 20

# social icons
show_social_icons: true
github_username: mscwilson
twitter_username: someTwitterUser

include:
  - _pages

collections:
  - projects
