plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO Stuff
author: Miranda
description: Messing around with Jekyll
lang: en
locale: en_GB
url: "https://mscwilson.github.io/portfolio"
baseurl: ""

# RSS feed
feed:
  posts_limit: 20
